<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Google JS tests" failures="10" time="0.01">
 <testcase name="MocksTest.satisfiedMocks" time="0.01"/>
 <testcase name="MocksTest.mockActions" time="0.01"/>
 <testcase name="MocksTest.mockInstance" time="0.01"/>
 <testcase name="MocksTest.unexpectedFunctionCall" time="0.01">
  <failure><![CDATA[Call matches no expectation.
    Arg 0: 19

Tried expectation at mocks_test.js:68, but arg 0 didn't match:
    Arg 0: 23

Tried expectation at mocks_test.js:67, but arg 0 didn't match:
    Arg 0: 17

Call to bar matches no expectation.
    Arg 0: 29]]></failure>
 </testcase>
 <testcase name="MocksTest.unexpectedMethodCall" time="0.01">
  <failure><![CDATA[Call to MyClass.doSomething matches no expectation.
    Arg 0: 17]]></failure>
 </testcase>
 <testcase name="MocksTest.unsatisfiedExpectations" time="0.01">
  <failure><![CDATA[Unsatisfied expectation at mocks_test.js:91:
    Arg 0: 19

Expected 1 call; called 0 times.

Unsatisfied expectation at mocks_test.js:94:
    Arg 0: 23

Expected 2 calls; called 1 time.

Unsatisfied expectation at mocks_test.js:99:
    Arg 0: 29

Expected 3 calls; called 4 times.]]></failure>
 </testcase>
 <testcase name="MocksTest.anotherTest" time="0.01"/>
 <testcase name="MocksTest.unsatisfiedExpectationsWithReferences" time="0.01">
  <failure><![CDATA[Unsatisfied expectation at mocks_test.js:130:
    Arg 0: is a reference to: { name: 'obj_1' }

Expected 1 call; called 0 times.

Unsatisfied expectation at mocks_test.js:133:
    Arg 0: is a reference to: { name: 'obj_2' }

Expected 2 calls; called 1 time.

Unsatisfied expectation at mocks_test.js:138:
    Arg 0: is a reference to: { name: 'obj_3' }

Expected 3 calls; called 4 times.]]></failure>
 </testcase>
 <testcase name="MocksTest.precedingExpectThat" time="0.01">
  <failure><![CDATA[Call matches no expectation.
    Arg 0: 23

Tried expectation at mocks_test.js:156, but arg 0 didn't match:
    Arg 0: 19

Unsatisfied expectation at mocks_test.js:156:
    Arg 0: 19

Expected 1 call; called 0 times.]]></failure>
 </testcase>
 <testcase name="MocksTest.expectCallWithNonMockFunction" time="0.01">
  <failure><![CDATA[mocks_test.js:162
TypeError: Supplied function is not a mock.]]></failure>
 </testcase>
 <testcase name="MocksTest.missingArguments" time="0.01">
  <failure><![CDATA[Call matches no expectation.
    (No arguments.)

Tried expectation at mocks_test.js:169, but number of arguments didn't match:
    Arg 0: is anything]]></failure>
 </testcase>
 <testcase name="MocksTest.tooManyArguments" time="0.01">
  <failure><![CDATA[Call matches no expectation.
    Arg 0: undefined
    Arg 1: 17

Tried expectation at mocks_test.js:183, but number of arguments didn't match:
    Arg 0: is anything

Call matches no expectation.
    Arg 0: undefined
    Arg 1: undefined

Tried expectation at mocks_test.js:183, but number of arguments didn't match:
    Arg 0: is anything]]></failure>
 </testcase>
 <testcase name="MocksTest.optionalArgument" time="0.01"/>
 <testcase name="MocksTest.optionalOrExactValueArgument" time="0.01">
  <failure><![CDATA[Call matches no expectation.
    Arg 0: undefined
    Arg 1: undefined

Tried expectation at mocks_test.js:211, but arg 1 didn't match:
    Arg 0: is anything
    Arg 1: is not present or 23

Call matches no expectation.
    Arg 0: undefined
    Arg 1: 24

Tried expectation at mocks_test.js:211, but arg 1 didn't match:
    Arg 0: is anything
    Arg 1: is not present or 23

Call matches no expectation.
    Arg 0: undefined
    Arg 1: 'taco'

Tried expectation at mocks_test.js:211, but arg 1 didn't match:
    Arg 0: is anything
    Arg 1: is not present or 23]]></failure>
 </testcase>
 <testcase name="MocksTest.sentinelMatcher" time="0.01">
  <failure><![CDATA[Call matches no expectation.
    (No arguments.)

Tried expectation at mocks_test.js:229, but number of arguments didn't match:
    Arg 0: is the missing arg sentinel]]></failure>
 </testcase>
</testsuite>
